[server]
## style file for the OSD
style = "/home/spacerat/.config/swayosd/style.css"

## on which height to show the OSD
top_margin = 0.05

## The maximum volume that can be reached in %
max_volume = 120

## show percentage on the right of the OSD
show_percentage = true

## set format for the media player OSD
playerctl_format = "{artist} - {title}"
## Available values:
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating

[client]
